name: Melius CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    environment: melius_env
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      SESSION_KEY: ${{ secrets.SESSION_KEY }}
      DB_URL: ${{ secrets.DB_URL }}
      PORT: ${{ secrets.PORT }}
      CI: true

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

  release:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v2
    - uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_email: "matteo68.mc@gmail.com"
        heroku_app_name: "melius-is2"